### ISSUE TITLE
Uninstall Instructions

### ISSUE THREAD

**Issue by zachmb** [Automattic/batcache#43]
There does not seem to be absolutely any instructions whatsoever across the entire internet that outline how to uninstall / delete Batcache.

I figured it would be obvious:

- Delete the batcache.php plugin file
- Delete the advanced_caceh.php file
- Remove all instances of the WP_CACHE variable in the wp-config.php file

Did all of this, and the files on my client's WordPress installation are still caching and it is absolutely impossible to develop with this on.

If anyone could please advise as to a way to disable this ridiculously pervasive plugin, I would greatly appreciate it.

Thanks!

**Comment by toddlahman** [comment]
Try deleting wp-content/object-cache.php, and the $memcached_servers line from wp-config.php. Batcache only works if object-cache.php is connecting WordPress to a Memcached instance, so now that Batcache is gone you are left with object caching.

**Comment by Viper007Bond** [comment]
`/wp-content/advanced-cache.php` is what WordPress tries to load super early (if the file exists) so that the file can handle serving cached pages.

Without that file, cached pages won't be served regardless of anything else.

Are you really, really sure that Batcache is still running despite deleting that file? If so, then perhaps your browser or your server is doing something odd.
