### ISSUE TITLE
No clear all method

### ISSUE THREAD

**Issue by spacedmonkey** [Automattic/batcache#62]
Currently there is no way to clear all urls stored in batcache. The batcache manager only seems to clear post page on update. However if there is a site wide change, such as changing theme, installing plugin or editting the customizer, all urls should be flushed. 

I think there is a way we could do this, without keeping track of all urls in cache. We could do something similar to advanced-post-cache. In the bit [code](https://github.com/Automattic/advanced-post-cache/blob/master/advanced-post-cache.php#L92-L97), when you send a flush, it changes the group. This effectively changes the salts the cache key and forces caches to regenerate. 

I was going to start work on this, but I thought it would be better to get people' thoughts first.

**Comment by skeltoac** [comment]
Thanks for this idea. It is not something we would add to batcache because it does not fit the main use cases and it is something you should be able to do inside of your batcache configuration logic or as part of a separate plugin. If you find it impossible to implement your idea without modifying batcache, then we can work together to make changes enabling your configuration or plugin.
