### ISSUE TITLE
Improve batcache manager

### ISSUE THREAD

**Issue by spacedmonkey** [Automattic/batcache#63]
So currently I have a PR #61 to add some improvements to cache clearing in batcache manger. But as I want to use batcache to cache for a much longer time than 5 minutes, I wanted to be sure that caches are clearing. To that end I wrote this https://github.com/spacedmonkey/batcache-manager . It builds on work of @skeltoac but clears out a lot more different kind of urls. I am still working on this, but I was wondering if people were interested in project. Should it be part of batcache? Is there anything else it could clear at the same time?

Related #62

**Comment by skeltoac** [comment]
The cache invalidation plugin was an afterthought that does not get much use. At least, we don't use it at all. Batcache does not aim very high for cache consistency. We recognize that WordPress can generate many more kinds of pages than we can keep track of (especially considering custom types); that the output depends on data that can change without notice to hooks; and that only a few of the URLs ever visited are visited enough to make caching worthwhile.

Our configuration is designed to prevent regenerating popular pages more often than necessary. Logged-in and recognized visitors are first-class citizens who always bypass the cache. For everyone else, we keep cache times short and don't worry about a little stale content being shown to passers-by. There are cases outside of those general principles so we use a batcache configuration containing lots of conditional blocks predicated on request variables.

To answer your question, I don't think batcache should have the cache invalidation logic. You are welcome to take what's there for your own plugin. In fact that would be great because then we could remove it from batcache. :)
